# Generated by Django 4.1.5 on 2023-03-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orpheus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(max_length=500)),
                ('bot_response', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
