# Generated by Django 4.1.5 on 2025-07-20 09:29

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orpheus', '0002_conversation_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_input',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='bot_response',
            field=models.TextField(),
        ),
    ]
