# Generated by Django 4.1.5 on 2025-07-20 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orpheus', '0003_remove_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
