services:
  - type: web
    name: MentalHealth
    env: python
    buildCommand: "pip install -r rq_test.txt"
    deployCommand: "python manage.py migrate"
    startCommand: "gunicorn MentalHealth.wsgi"

