services:
  - type: web
    name: MentalHealth
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn MentalHealth.wsgi"
    deployCommand: "python manage.py migrate"
