services:
  - type: web
    name: MentalHealth
    env: python
    buildCommand: "pip install -r requirements.txt"
    deployCommand: "python manage.py migrate"
    startCommand: "gunicorn MentalHealth"

