services:
  - type: web
    name: MentalHealth
    env: python
    buildCommand: "pip install -r rq_test.txt"
    deployCommand: "python manage.py migrate"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT MentalHealth.wsgi:application"

